# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba47335400d24e8c25a7bca1358a35fee013689dd127d02d0e42411fc1229709f2320ce68cfb5b592b287f303a0ebedd86e07e40a4cc02b077e80ee599b154b

test:
  secret_key_base: 8aa97e4da9551f07859476660521a85e90b0c835d092a277b2e780a85ca6784608e760442f7ae03877369893a4c26d2b304f6039992f49eaab96d2221e2f883f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
